# Generated by Django 3.0.14 on 2023-06-01 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_test.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_column='create_time', default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('name', models.CharField(blank=True, help_text='姓名', max_length=100, verbose_name='姓名')),
                ('type', models.SmallIntegerField(choices=[(0, '管理员'), (1, '顾客'), (2, '商家')], default=1, verbose_name='用户类型')),
                ('business_id', django_test.db.models.fields.UnsignedBigIntegerField(help_text='绑定商家 ID', null=True, verbose_name='绑定商家 ID')),
                ('customer_id', django_test.db.models.fields.UnsignedBigIntegerField(help_text='绑定顾客 ID', null=True, verbose_name='绑定顾客 ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否是管理权限组成员')),
                ('is_enabled', models.BooleanField(default=True, help_text='是否启用，启用才可以登录', verbose_name='是否启用')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账号')),
            ],
            options={
                'db_table': 'user',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('expires', models.DateTimeField(auto_now_add=True, verbose_name='Expires')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'APIToken',
                'verbose_name_plural': 'APITokens',
                'db_table': 'sso2_apitoken',
            },
        ),
    ]
