# Generated by Django 3.0.14 on 2023-05-25 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_column='create_time', default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('name', models.CharField(blank=True, help_text='姓名', max_length=100, verbose_name='姓名')),
                ('type', models.SmallIntegerField(choices=[(0, '管理员'), (1, '普通用户'), (2, 'VIP')], default=1, verbose_name='用户类型')),
                ('passwd', models.CharField(blank=True, help_text='密码', max_length=100, verbose_name='密码')),
            ],
            options={
                'db_table': 'user',
                'abstract': False,
            },
        ),
    ]
