# Generated by Django 3.0.14 on 2023-05-26 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_column='create_time', default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('name', models.CharField(blank=True, help_text='姓名', max_length=100, verbose_name='姓名')),
                ('type', models.SmallIntegerField(choices=[(0, '管理员'), (1, '普通用户'), (2, 'VIP')], default=1, verbose_name='用户类型')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账号')),
            ],
            options={
                'db_table': 'user',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('expires', models.DateTimeField(auto_now_add=True, verbose_name='Expires')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'APIToken',
                'verbose_name_plural': 'APITokens',
                'db_table': 'sso2_apitoken',
            },
        ),
    ]
