# Generated by Django 3.0.14 on 2023-05-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否是管理权限组成员'),
        ),
    ]
