# Generated by Django 3.0.14 on 2023-05-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BaseUser',
        ),
    ]
