# Generated by Django 3.0.14 on 2023-05-26 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_user', '0003_baseuser_is_enabled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseUser',
            new_name='UserProfile',
        ),
    ]
