# Generated by Django 3.0.14 on 2023-05-26 16:04

from django.db import migrations, models
import django_test.db.models.base
import django_test.db.models.deletion
import django_test.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('create_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=django_test.db.models.base.current_user_id, verbose_name='创建人 ID')),
                ('update_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=0, verbose_name='更新人 ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标志', verbose_name='是否已删除')),
                ('note', models.CharField(default='', max_length=512, null=True, verbose_name='备注')),
                ('id', django_test.db.models.fields.UnsignedBigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='商家账户名称', max_length=128, verbose_name='商家账户名称')),
                ('business_url', models.CharField(help_text='商家头像url', max_length=128, verbose_name='商家头像url')),
                ('context', models.TextField(help_text='商家简介', verbose_name='商家简介')),
                ('be_attention_count', django_test.db.models.fields.UnsignedIntegerField(default=0, verbose_name='被多少顾客关注')),
            ],
            options={
                'db_table': 'business',
                'abstract': False,
            },
            bases=(django_test.db.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('create_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=django_test.db.models.base.current_user_id, verbose_name='创建人 ID')),
                ('update_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=0, verbose_name='更新人 ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标志', verbose_name='是否已删除')),
                ('note', models.CharField(default='', max_length=512, null=True, verbose_name='备注')),
                ('id', django_test.db.models.fields.UnsignedBigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='商家账户名称', max_length=128, verbose_name='顾客账户名称')),
                ('customer_url', models.CharField(help_text='顾客头像url', max_length=128, verbose_name='顾客头像url')),
                ('context', models.TextField(help_text='顾客简介', verbose_name='顾客简介')),
                ('attention_count', django_test.db.models.fields.UnsignedIntegerField(default=0, verbose_name='关注的店铺数量')),
            ],
            options={
                'db_table': 'customer',
                'abstract': False,
            },
            bases=(django_test.db.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
    ]
