# Generated by Django 3.0.14 on 2023-05-30 14:33

from django.db import migrations, models
import django.db.models.manager
import django_test.db.models.base
import django_test.db.models.deletion
import django_test.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionLink',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('create_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=django_test.db.models.base.current_user_id, verbose_name='创建人 ID')),
                ('update_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=0, verbose_name='更新人 ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标志', verbose_name='是否已删除')),
                ('note', models.CharField(default='', max_length=512, null=True, verbose_name='备注')),
                ('id', django_test.db.models.fields.UnsignedBigAutoField(editable=False, primary_key=True, serialize=False)),
                ('customer_id', django_test.db.models.fields.UnsignedBigIntegerField(help_text='顾客id', verbose_name='顾客id')),
                ('business_id', django_test.db.models.fields.UnsignedBigIntegerField(help_text='关注商家id', verbose_name='关注商家id')),
            ],
            options={
                'db_table': 'attention_link',
                'abstract': False,
            },
            bases=(django_test.db.models.deletion.ModelOnDeleteMixin, models.Model),
            managers=[
                ('objects_internal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('create_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=django_test.db.models.base.current_user_id, verbose_name='创建人 ID')),
                ('update_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=0, verbose_name='更新人 ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标志', verbose_name='是否已删除')),
                ('note', models.CharField(default='', max_length=512, null=True, verbose_name='备注')),
                ('id', django_test.db.models.fields.UnsignedBigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='商家账户名称', max_length=128, verbose_name='商家账户名称')),
                ('business_url', models.CharField(help_text='商家头像url', max_length=128, null=True, verbose_name='商家头像url')),
                ('context', models.TextField(help_text='商家简介', null=True, verbose_name='商家简介')),
                ('be_attention_count', django_test.db.models.fields.UnsignedIntegerField(default=0, verbose_name='被多少顾客关注')),
            ],
            options={
                'db_table': 'business',
                'abstract': False,
            },
            bases=(django_test.db.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('create_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=django_test.db.models.base.current_user_id, verbose_name='创建人 ID')),
                ('update_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=0, verbose_name='更新人 ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标志', verbose_name='是否已删除')),
                ('note', models.CharField(default='', max_length=512, null=True, verbose_name='备注')),
                ('id', django_test.db.models.fields.UnsignedBigAutoField(editable=False, primary_key=True, serialize=False)),
                ('commodity_name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('is_sales', models.BooleanField(default=True, verbose_name='是否还在售卖')),
                ('score', models.FloatField(default=0, help_text='业绩分-积分制, +10为加10分，-10为减10分')),
                ('price', models.FloatField(default=0, help_text='商品价格')),
                ('context', models.TextField(help_text='商品介绍', null=True, verbose_name='商品介绍')),
                ('commodity_url', models.CharField(help_text='商品地址', max_length=128, verbose_name='商品地址')),
            ],
            options={
                'db_table': 'commodity',
                'abstract': False,
            },
            bases=(django_test.db.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('create_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=django_test.db.models.base.current_user_id, verbose_name='创建人 ID')),
                ('update_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=0, verbose_name='更新人 ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标志', verbose_name='是否已删除')),
                ('note', models.CharField(default='', max_length=512, null=True, verbose_name='备注')),
                ('id', django_test.db.models.fields.UnsignedBigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='商家账户名称', max_length=128, verbose_name='顾客账户名称')),
                ('customer_url', models.CharField(help_text='顾客头像url', max_length=128, null=True, verbose_name='顾客头像url')),
                ('context', models.TextField(help_text='顾客简介', null=True, verbose_name='顾客简介')),
                ('attention_count', django_test.db.models.fields.UnsignedIntegerField(default=0, verbose_name='关注的店铺数量')),
            ],
            options={
                'db_table': 'customer',
                'abstract': False,
            },
            bases=(django_test.db.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('create_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=django_test.db.models.base.current_user_id, verbose_name='创建人 ID')),
                ('update_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=0, verbose_name='更新人 ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标志', verbose_name='是否已删除')),
                ('note', models.CharField(default='', max_length=512, null=True, verbose_name='备注')),
                ('id', django_test.db.models.fields.UnsignedBigAutoField(editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(help_text='店铺名称', max_length=128, verbose_name='店铺名称')),
                ('shop_url', models.CharField(help_text='店铺url', max_length=128, verbose_name='店铺url')),
                ('shop_pic', models.CharField(help_text='店铺图片url', max_length=128, verbose_name='店铺图片url')),
                ('content', models.TextField(help_text='店铺简介', null=True, verbose_name='店铺简介')),
            ],
            options={
                'db_table': 'shop',
                'abstract': False,
            },
            bases=(django_test.db.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShopStyle',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('create_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=django_test.db.models.base.current_user_id, verbose_name='创建人 ID')),
                ('update_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=0, verbose_name='更新人 ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标志', verbose_name='是否已删除')),
                ('note', models.CharField(default='', max_length=512, null=True, verbose_name='备注')),
                ('id', django_test.db.models.fields.UnsignedBigAutoField(editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=128, verbose_name='店铺类型')),
            ],
            options={
                'db_table': 'shop_style',
                'abstract': False,
            },
            bases=(django_test.db.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShopToStyle',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('create_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=django_test.db.models.base.current_user_id, verbose_name='创建人 ID')),
                ('update_user_id', django_test.db.models.fields.UnsignedBigIntegerField(default=0, verbose_name='更新人 ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标志', verbose_name='是否已删除')),
                ('note', models.CharField(default='', max_length=512, null=True, verbose_name='备注')),
                ('id', django_test.db.models.fields.UnsignedBigAutoField(editable=False, primary_key=True, serialize=False)),
                ('shop_id', django_test.db.models.fields.UnsignedBigIntegerField(verbose_name='店铺id')),
                ('shop_style_id', django_test.db.models.fields.UnsignedBigIntegerField(verbose_name='店铺类型id')),
            ],
            options={
                'db_table': 'shop_to_style',
                'abstract': False,
            },
            bases=(django_test.db.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
    ]
