# Generated by Django 3.0.14 on 2023-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_url',
            field=models.CharField(help_text='商家头像url', max_length=128, null=True, verbose_name='商家头像url'),
        ),
        migrations.AlterField(
            model_name='business',
            name='context',
            field=models.TextField(help_text='商家简介', null=True, verbose_name='商家简介'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='context',
            field=models.TextField(help_text='顾客简介', null=True, verbose_name='顾客简介'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_url',
            field=models.CharField(help_text='顾客头像url', max_length=128, null=True, verbose_name='顾客头像url'),
        ),
    ]
