# Generated by Django 3.0.14 on 2023-05-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_hrm', '0002_auto_20230530_1434'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attentionlink',
            table='customer_attention_link',
        ),
    ]
